#!/usr/bin/env bash

if [ ! -x "./checker_linux" ]; then
	echo "ERROR: checker_linux not found" >&2
	exit 1;
fi

if [ ! -x "./push_swap" ]; then
	echo "ERROR: push_swap not found";
	exit 1;
fi

if [ ${#} -lt 2 ]; then
        echo "ERROR! usage: ./test <STACK SIZE> <NB ITERATIONS> [JOBSMAX=8]" >&2;
        exit 1;
fi

SSIZE=${1};
NITER=${2};
JOBSMAX=${3:-8};

DIR=$(mktemp -d /tmp/push_swap_XXXXXXXX);
trap "rm -rf ${DIR}" INT QUIT TERM EXIT;

run()
{
        ARGS=$(shuf -i 1-${SSIZE} | xargs);
        TMP=$(mktemp -p ${DIR});
        RES=$(./push_swap ${ARGS} | tee ${TMP} | ./checker_linux ${ARGS});
		echo "${RES};$(cat ${TMP} | wc -l);${ARGS};$(cat ${TMP} | xargs);";
        echo -n "." >&2;
}

TMP=$(mktemp -p ${DIR});

for i in $(seq ${NITER}); do
	if [ $(jobs | wc -l) -ge ${JOBSMAX} ]; then
		wait -n
	fi
	run &
done > ${TMP};
wait;
echo;

if [ -n "$(cat ${TMP} | awk -F ';' '{print $1}' | grep Error)" ]; then
        echo "ERROR from push_swap";
        cat ${TMP}													\
			| grep Error											\
			| head -1												\
			| awk -F ';' '{printf "STACK: %s\n\nOUTPUT: %s\n", $3, $4}';
        exit 1;
fi

NOPS=$(cat ${TMP} | awk -F ';' '{print $2}' | xargs);

echo "MAX=$(printf '%s\n' ${NOPS} | sort -n | tail -1)";
echo "AVG=$(( $(echo ${NOPS} | sed 's/ / + /g' | bc) / $(echo ${NOPS} | wc -w) ))";
